In [1]:
#!pip install tensorflow
#!pip install -q tensorflow-datasets


In [52]:
import numpy as np

import pickle
from bs4 import BeautifulSoup # remove the html tags like <br> <tr> ....
import re


import tensorflow as tf
from tensorflow.keras import datasets, preprocessing, models, layers
from tensorflow.keras.preprocessing.sequence import pad_sequences


vocab_size = 10000 # number of knowing Words 
embedding_dim = 16 # similarities dimension for word embedding function 
max_length = 200 



    
print(tf.__version__)

2.4.1


In [53]:


tokenizer=pickle.load(open("tokenizer.pkl", "rb"))

model = tf.keras.models.load_model('Sequential.h5') #same file path
model.summary()


Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 200, 16)           160000    
_________________________________________________________________
separable_conv1d_1 (Separabl (None, 67, 10)            250       
_________________________________________________________________
batch_normalization_1 (Batch (None, 67, 10)            40        
_________________________________________________________________
max_pooling1d_1 (MaxPooling1 (None, 33, 10)            0         
_________________________________________________________________
global_average_pooling1d_1 ( (None, 10)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 10)                110       
_________________________________________________________________
dense_3 (Dense)              (None, 1)                

In [54]:
Dict={0:"Negative",1:"Positive"}

def strip_special_chars(st):
    st = BeautifulSoup(st, "lxml").text
    my_pattern = '[A-Za-z0-9.! ]+'
    return ''.join(re.findall(my_pattern, st))

def text_convertore(text,max_length=200):
    text=strip_special_chars(text.lower())
    test=tokenizer.texts_to_sequences([text])
    
    paded_test=pad_sequences(test,maxlen=max_length,padding="post")
    
    return paded_test


### Load IMDB Dataset : Inclouding reviews and emotions 

In [55]:
text="""
In order to realize the breakthroughs of the future, we’ve revolutionized how we work today. We're unlocking the pill to reveal Pfizer’s DNA: the power of science."""
test=text_convertore(text,max_length=200)


print(test)

print(model.predict(test))
print(Dict[model.predict_classes(test)[0][0]])


[[   8  645    6  900    2    1    5    2  689 1932    1   86   71  158
   625   66    1    2    1    6 2544    1    1    2  666    5 1120    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0   

array([[0.9742953]], dtype=float32)

In [44]:
model.predict_classes(test)

array([[1]])

In [47]:
model.predict_proba(test)

array([[0.9742953]], dtype=float32)